// All on-screen copy lives here so a zh.ts can be added later
// without touching the scene code.

export const copy = {
  brand: {
    mark: "Custom AI Solutions",
    suffix: "by Tony Teng",
    url: "build.tonyteng.dev",
    byline: "Custom AI Solutions",
  },

  hook: {
    line1: "Your busywork.",
    line2: "Handled by AI.",
    sub: "Custom-built for the way your business actually runs.",
    chores: [
      "Re-typing data into supplier portals",
      "Keying invoices into the books",
      "Answering “where’s my order?” at midnight",
    ],
  },

  form: {
    index: "01",
    label: "Form-filling agent",
    title: "Add a row. An agent fills the form — on any site, around the clock.",
    sheetName: "Supplier onboarding",
    columns: ["Company", "Contact", "ABN", "Status"],
    doneRows: [
      ["Brightwater Joinery", "Lena Marsh", "38 116 402 771", "Done · 11:02 PM"],
      ["Ostrom Coffee Co.", "Dev Anand", "72 603 118 945", "Done · 12:40 AM"],
    ],
    newRow: ["Harbourline Freight", "Callum Reyes", "51 824 753 556"],
    nextRow: ["Pellow Ceramics", "Ines Kowalczyk", "64 219 830 402"],
    queued: "Queued",
    watching: "Watching “Supplier onboarding” · every 30s",
    doneAt: "Done · 02:14 AM",
    agentName: "Agent",
    agentTag: "24/7",
    clock: "02:14 AM",
    url: "suppliers.kestrelgroup.com.au/register",
    pageTitle: "Supplier registration",
    pageSub: "Kestrel Group · Vendor portal",
    fields: [
      { label: "Company name", value: "Harbourline Freight" },
      { label: "Contact name", value: "Callum Reyes" },
      { label: "ABN", value: "51 824 753 556" },
      { label: "Email", value: "callum@harbourline.com.au" },
      { label: "Category", value: "Freight & logistics" },
    ],
    consent: "I confirm these details are correct",
    submit: "Submit registration",
    success: "Registration received",
    successRef: "Reference KS-20931",
    log: [
      "new row detected · Harbourline Freight",
      "opened suppliers.kestrelgroup.com.au",
      "filled 5 fields · ticked consent",
      "submitted · ref KS-20931",
      "sheet updated",
      "new row detected · Pellow Ceramics",
    ],
  },

  invoice: {
    index: "02",
    label: "Inbox agent",
    title: "Invoices read, logged and checked — before you open your inbox.",
    inboxTitle: "Inbox",
    emails: [
      { from: "Northgate Packaging", subject: "Invoice INV-2291", time: "6:12 AM", attach: true },
      { from: "Rowan Hale", subject: "Re: Q4 stand-up notes", time: "Yesterday", attach: false },
      { from: "Tallis & Co.", subject: "September statement", time: "Yesterday", attach: true },
      { from: "Marlow Signage", subject: "Proof v3 attached", time: "Mon", attach: true },
    ],
    secondEmail: { from: "Tallis & Co.", subject: "Invoice INV-2297", time: "6:31 AM", attach: true },
    pdf: {
      vendor: "Northgate Packaging Pty Ltd",
      number: "INV-2291",
      issued: "30 Sep 2026",
      due: "14 Oct 2026",
      po: "PO-7713",
      lines: [
        ["Corrugated cartons 600×400", "1,200", "$2,736.00"],
        ["Void fill, recycled (bales)", "40", "$1,160.00"],
        ["Pallet delivery", "1", "$0.00"],
      ],
      subtotal: "$3,896.00",
      gst: "$389.60",
      total: "$4,285.60",
    },
    pdf2: {
      vendor: "Tallis & Co. Pty Ltd",
      number: "INV-2297",
      issued: "02 Oct 2026",
      due: "16 Oct 2026",
      po: "PO-7720",
      lines: [
        ["Brass hinges, 100mm", "120", "$1,104.00"],
        ["Drawer runners, soft-close", "42", "$647.64"],
        ["Freight", "1", "$12.00"],
      ],
      subtotal: "$1,763.64",
      gst: "$176.36",
      total: "$1,940.00",
    },
    log: [
      "opened INV-2291.pdf",
      "extracted vendor, total, due date, PO",
      "PO-7713 matches · logged",
      "opened INV-2297.pdf · Tallis & Co.",
      "PO-7720 approved for $1,490.00 · flagged",
    ],
    totalLabel: "Logged this week",
    totalBefore: 3662,
    totalAfter: 7947.6,
    ledgerTitle: "Accounts payable",
    ledgerCols: ["Vendor", "Amount", "Due", "PO", "Status"],
    ledgerRows: [
      ["Marlow Signage", "$612.00", "02 Oct", "PO-7702", "Logged"],
      ["Brightwater Joinery", "$3,050.00", "09 Oct", "PO-7708", "Logged"],
    ],
    newRow: ["Northgate Packaging", "$4,285.60", "14 Oct", "PO-7713", "Logged"],
    flaggedRow: ["Tallis & Co.", "$1,940.00", "16 Oct", "PO-7720", "Review"],
    scanLabel: "Reading invoice",
    chips: ["Vendor", "Total", "Due", "PO"],
    toastTitle: "Flagged for review",
    toastBody: "INV-2297 is $1,940.00 — PO-7720 was approved for $1,490.00.",
  },

  support: {
    index: "03",
    label: "Support agent",
    title: "Trained on your docs. Wired into your tools. Knows when to call a human.",
    shop: "Loomwell Home",
    widgetTitle: "Support",
    online: "Replies instantly",
    chat1: {
      time: "11:48 PM",
      customer: "Hi, can I change the delivery address on order #4821 to 18 Rowe St, Fitzroy?",
      tools: [
        { text: "Found order #4821", src: "Shopify" },
        { text: "Checked Shipping Policy §3", src: "Docs" },
        { text: "Updated delivery address", src: "Shopify" },
      ],
      reply: "Done. Order #4821 now ships to 18 Rowe St, Fitzroy. It leaves our warehouse tomorrow morning.",
    },
    chat2: {
      time: "12:03 AM",
      customer: "My lamp arrived cracked. It’s been 45 days, can I still get a refund?",
      tools: [
        { text: "Checked Returns Policy §2 · 30-day window", src: "Docs" },
        { text: "Outside policy · needs a person", src: "Handoff" },
      ],
      reply: "I’ve passed this to our team with your photos and order details. You’ll hear back by 9 AM.",
      approved: "Good news: your refund of $189.00 has been approved. Sorry about the lamp.",
    },
    slack: {
      workspace: "Loomwell",
      channel: "support-escalations",
      channels: ["general", "orders", "support-escalations", "warehouse"],
      bot: "Support Agent",
      botTime: "12:03 AM",
      heading: "Refund request outside policy",
      facts: [
        ["Customer", "Aroha Tane · 3 past orders"],
        ["Order", "#4793 · Arc floor lamp · $189.00"],
        ["Issue", "Arrived cracked · 2 photos attached"],
        ["Policy", "Bought 45 days ago · window is 30"],
      ],
      suggestion: "Suggested: full refund as goodwill",
      approve: "Approve refund",
      reply: "Reply myself",
      approvedBy: "Approved by Dana Whitlock · 8:52 AM",
    },
    stats: [
      { value: 37, label: "resolved overnight" },
      { value: 3, label: "handed to your team" },
      { value: 0, label: "customers left waiting" },
    ],
  },

  how: {
    label: "How it works",
    title: "See it work before you pay.",
    steps: [
      { n: "01", title: "Tell me what you need", body: "A few sentences in plain English is enough." },
      { n: "02", title: "Get a working demo", body: "Built on your real workflow. Nothing to pay yet." },
      { n: "03", title: "Like it? Then we build it out", body: "You pay only when you decide to go ahead." },
    ],
  },

  end: {
    lead: "Tell me what to automate.",
    extra: "Agents, integrations, websites, games — if you can describe it, I can build it.",
  },

  // ---------- 30-second cut ----------
  short: {
    smash: {
      tasks: [
        "Type receipts into Xero",
        "Reply to the same email",
        "Fill in the same form",
        "Copy details into 3 apps",
        "Call back a missed call",
        "Write another quote",
        "Send appointment reminders",
        "Answer “where’s my order?”",
        "Update the spreadsheet",
        "Build Monday’s report",
        "Confirm tomorrow’s bookings",
        "Rename the photos",
        "Chase the paperwork",
        "Re-type a supplier bill",
        "Book the same meeting",
        "Paste the same reply",
      ],
      counts: ["×38", "×112", "×64", "×64", "×27", "×15", "×140", "×75", "×90", "×52", "×36", "×300", "×21", "×48", "×19", "×210"],
      word: "SMASH",
      rest: "your repetitive work.",
      sub: "No tech skills needed. Just tell me what eats your week.",
    },
    helper: "AI helper",
    form: {
      index: "01",
      label: "Online forms",
      title: "Type it once. The forms fill themselves.",
      steps: ["You add a row to your sheet", "Your AI helper fills in the website form", "Sent. Reference saved for you"],
      sheet: "New suppliers",
      sheetApp: "Google Sheet",
      cols: ["Business", "Contact", "Email"],
      rows: [
        ["Brightwater Joinery", "Lena Marsh", "lena@brightwater.au"],
        ["Ostrom Coffee Co.", "Dev Anand", "dev@ostrom.coffee"],
      ],
      newRow: ["Harbourline Freight", "Callum Reyes", "callum@harbourline.au"],
      url: "suppliers.kestrelgroup.com.au",
      page: "Supplier sign-up",
      fields: [
        { label: "Business name", value: "Harbourline Freight" },
        { label: "Contact name", value: "Callum Reyes" },
        { label: "Email", value: "callum@harbourline.au" },
      ],
      submit: "Submit",
      done: "Sent",
      ref: "Ref KS-20931",
    },
    web: {
      index: "02",
      label: "Websites",
      title: "Your product, on a website that sells.",
      steps: ["Send a few photos and notes", "Get a site built around your product", "Tuned to load fast and get found"],
      notesTitle: "Your notes",
      notes: ["Handmade ceramic mugs", "Dishwasher safe", "$38 each", "Ships in 2 days"],
      url: "kilnandco.com.au",
      brand: "Kiln & Co.",
      nav: ["Shop", "Our story", "Contact"],
      headline: "Handmade mugs for slow mornings.",
      sub: "Thrown by hand in small batches. Dishwasher safe.",
      cta: "Shop mugs · $38",
      features: ["Handmade", "Dishwasher safe", "Ships in 2 days"],
      scores: [
        { label: "Speed", value: 98 },
        { label: "SEO", value: 100 },
        { label: "Mobile", value: 100 },
      ],
      search: {
        title: "Kiln & Co. · Handmade ceramic mugs",
        url: "kilnandco.com.au",
        desc: "Thrown by hand in small batches. Dishwasher safe. Ships in 2 days.",
      },
    },
    receipts: {
      index: "03",
      label: "Custom apps",
      title: "A receipt app, built just for you.",
      steps: ["Snap a receipt in your own app", "Your AI helper reads the store, date and total", "Saved straight to your cloud or database"],
      appName: "Receipts",
      appOwner: "Harbour Plumbing",
      scan: "Scan receipt",
      reading: "Reading…",
      uploaded: "Uploaded",
      store: "Hammer & Co. Hardware",
      date: "26 Sep 2026",
      items: [
        ["Timber 90×45 (6)", "$62.40"],
        ["Screws, box", "$16.00"],
        ["Sandpaper pack", "$8.00"],
      ],
      gst: "$7.85",
      total: "$86.40",
      db: "Your database",
      table: "receipts",
      syncing: "Syncing…",
      synced: "Synced to your cloud",
      cols: ["Store", "Date", "Total", "Category", "Photo"],
      rows: [
        { store: "Southside Fuel", date: "24 Sep", total: "$92.10", cat: "Vehicle" },
        { store: "Paper Street Office", date: "25 Sep", total: "$43.95", cat: "Office" },
      ],
      newRow: { store: "Hammer & Co. Hardware", date: "26 Sep", total: "$86.40", cat: "Materials" },
    },
    connect: {
      label: "No new software",
      title: "Works with the apps you already use.",
      core: "AI helper",
      tools: ["Xero", "Gmail", "Shopify", "Google Calendar", "MYOB", "Outlook", "Your website", "Spreadsheets"],
    },
    pay: {
      label: "How it works",
      title: "See it work before you pay.",
      steps: ["Tell me what eats your week", "Get a free working demo", "Pay only if you go ahead"],
    },
    end: {
      line1: "Less busywork.",
      line2: "More business.",
      sub: "Boost your efficiency. No tech skills needed.",
      extra: "Custom AI Solutions · Free demo first",
    },
  },
} as const;

export type Copy = typeof copy;
